function escStr = Escape(str, escChrs, escSubs)
% Escape special LaTeX characters
%
% Following chars will be escaped by default:
% %, $, #, _, &, {, }, \, ~
%
% Inputs:
%   str       : input string
%   [escChrs] : cell array with chars to be escaped, optional
%   [escSubs] : cell array with escaped characters, optional
%               (must be the same length as 'escChrs')
%
% Outputs:
%   ret       : output string

if nargin == 1
    escChrs = { ...
        '%', ...
        '$', ...
        '#', ...
        '_', ...
        '&', ...
        '{', ...
        '}', ...
        '\', ...
        '~', ...
        };
    
    escSubs = { ...
        '{\%}', ...
        '{\$}', ...
        '{\#}', ...
        '{\_}', ...
        '{\&}', ...
        '{\{}', ...
        '{\}}', ...
        '{\textbackslash}', ...
        '{\textasciitilde}', ...
        };
end

compFun = @(c) cellfun(@(x) x == c, escChrs);
replFun = @(c) escSubs{compFun(c)};
idx = arrayfun(@(c) any(compFun(c)), str);
escStr = num2cell(str);
escStr(idx) = cellfun(replFun, escStr(idx), 'UniformOutput', false);
escStr = strjoin(escStr, '');
end